#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Commiting...'

# Check ESLint Standards
yarn lint ||
(
    echo '🔨❌ You have a problem in your code. Check linter 🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'

npx lint-staged
